AppVeyor: Integrate test suite base on GTest 1.8.1
A few notes:
- FindGTest.cmake checks for gtest/gtest.h as well, not just .lib files

- GTest compilation fails with
  error C2220: warning treated as error - no 'object' file generated
  with older versions of MSVC, e.g. with
  - Visual Studio 10 2010
  - Visual Studio 11 2012
  - Visual Studio 12 2013

- GTest is guilt with /MT so we need to make uriparser use /MT as well