Fix GCC 4.9 -Werror=uninitialized issue
uriparser\src\UriParse.c:2026:24: error: 'parser.uri' is used uninitialized in this function [-Werror=uninitialized]

    URI_TYPE(Uri) * const uriBackup = state->uri;
                          ^

uriparser\src\UriParse.c:2210:24: note: 'parser' was declared here

    URI_TYPE(ParserState) parser;
                          ^

When calling ResetParserState, parser.url is read into a temporary
variable while the parser is reset. In this case, parser is declared on
the stack, so we have an unitilized value

This can be resolved, by calling ResetParserState after we have assigned
parser.uri