fix aot debuginfo strings const-correctness
Make strings of all structs in debug_info.h const.
This both fix compilation errors like e.g.
XXX(NNN): error C2440: 'initializing': cannot convert from 'initializer list' to 'das::FuncInfo'
(in msvc+/permissive-) and simplifies overall code as well (e.g. remove need for manual casts)

Also fix incorrect 64 bit hashes on 32 bit MS-platforms (unsigned long is 32 bit on win32,
use appropriate macro UINT64_C instead)