Exception: write stack to err on exception
Why: this stack represent error, there no reason to write it to
out, because other messages in this function we write to err