proof of concept, more detailed runtime error messages ``` options gen2
struct Foo {
    a : int = 5
}

[export]
def main {
    var foo : Foo?
    let x = foo.a // used to produce EXCEPTION: dereferencing null pointer at D:\Work\daScript/examples/test/misc/hello_world.das:10:15
    print("x = {x}\n")
}
```

now produces

```
EXCEPTION: dereferencing null pointer, foo is null
 at D:\Work\daScript/examples/test/misc/hello_world.das:10:15
```